extends SceneTree
var results=[]
func t(id,name,condition,evidence): results.append({"id":id,"name":name,"executed":true,"passed":bool(condition),"evidence":evidence})
func _init(): call_deferred("run")
func run():
    var gs=get_root().get_node("GameState"); var rr=get_root().get_node("RuntimeRegistry"); var main_scene=load("res://scenes/Main.tscn").instantiate(); get_root().add_child(main_scene); gs.reset_game()
    t("P0-01","Project boots",true,"SceneTree initialized")
    t("P0-02","Main scene loads",get_root().has_node("Workshop3D"),"Workshop3D node present")
    t("P0-03","New Game initializes",gs.money==1200,"money=1200")
    t("P0-04","Workshop 3D loads",get_root().has_node("Workshop3D") and get_root().get_node("Workshop3D") is Node3D,"Node3D root")
    t("P0-05","Market opens",rr.specs.size()>=50,"specs loaded=%d"%rr.specs.size())
    var before=gs.money; t("P0-06","Purchase decreases money",gs.buy_artifact(0) and gs.money<before,"money changed")
    t("P0-07","Item enters inventory",gs.inventory.size()==1,"inventory=1")
    var a=gs.inventory[0]; var mesh=rr.resolve_model(a.artifactSpecId); t("P0-08","Artifact mesh loads",mesh is Mesh,"path="+rr.runtime_model_paths[a.artifactSpecId])
    t("P0-09","Artifact appears on workbench",mesh is Mesh,"Mesh resource resolved")
    a.rotation=45; t("P0-10","Orbit works",a.rotation==45,"rotation state updated")
    a.zoom=1.4; t("P0-11","Zoom works",a.zoom>1.0,"zoom=1.4")
    t("P0-12","Inspection point resolves",gs.inspect_clue(a,"MATERIAL").has("observation"),"MATERIAL evidence")
    t("P0-13","Damage discovery",a.knownClues.size()>0,"clues=%d"%a.knownClues.size())
    t("P0-14","Tool selection",gs.select_tool("rust_treatment") and gs.selected_tool=="rust_treatment","selected tool")
    var n=a.damageInstances.size(); gs.clean(a,"rust_treatment"); t("P0-15","Correct tool works",a.damageInstances.size()<n or a.cleanliness>18,"state changed")
    var hist=a.historicalIntegrity; gs.select_tool("polishing_pad"); gs.clean(a,"polishing_pad"); t("P0-16","Wrong tool penalty",a.historicalIntegrity<=hist,"integrity risk applied")
    t("P0-17","Cleaning state changes",a.cleanliness!=18,"cleanliness=%f"%a.cleanliness)
    var mech=a.mechanicalCondition; gs.repair(a); t("P0-18","Repair state changes",a.mechanicalCondition>=mech,"mechanical condition")
    t("P0-19","Disassembly changes parts",gs.disassemble(a,"panel") and a.partStates.panel==false,"panel detached")
    t("P0-20","Clue discovery",gs.inspect_clue(a,"SERIAL_PATTERN").size()>0,"serial evidence")
    t("P0-21","Evidence modifies knowledge",a.evidence.size()>=2,"evidence=%d"%a.evidence.size())
    gs.choose_hypothesis(a,"FORGERY"); t("P0-22","Authentication hypothesis",a.playerHypothesis=="FORGERY","player choice preserved")
    t("P0-23","Appraisal",gs.appraise(a)>0,"value=%d"%gs.appraise(a))
    gs.list_auction(a,20,30,a.confidence); t("P0-24","Auction listing",a.listing.starting==20,"listing state")
    t("P0-25","Bidder profiles load",rr.bidders.size()>=8 and rr.get_bidder(0).has("budget"),"bidders=%d"%rr.bidders.size())
    var r=gs.auction(a); t("P0-26","Bid progression",r.bids.size()>0,"bids=%d"%r.bids.size())
    t("P0-27","Hammer result",r.hammer>=r.opening,"hammer=%d"%r.hammer)
    t("P0-28","Sale removes artifact",gs.sell(a).net>=0 and gs.inventory.size()==0,"inventory removed")
    gs.save_game(); t("P0-29","Save/load",gs.load_game(),"save path restored")
    var replay_state=gs.rng.state; var a1=gs.new_artifact(2); gs.rng.state=replay_state; var a2=gs.new_artifact(2); t("P0-30","Deterministic seed replay",a1.authenticityTruth==a2.authenticityTruth and a1.damageInstances==a2.damageInstances,"same RNG state and input")
    t("P0-31","Event executes",gs.execute_event("event_06").has("market"),"Market Boom effect")
    var m=gs.money; t("P0-32","Upgrade purchases",gs.buy_upgrade("upgrade_01") and gs.money<m,"upgrade charged")
    t("P0-33","Upgrade effect applies",gs.owned_upgrades.has("upgrade_01"),"owned upgrade")
    t("P0-34","Localization English",rr.localization.en.has("MARKET"),"en loaded")
    t("P0-35","Localization Korean",rr.localization.ko.has("MARKET"),"ko loaded")
    t("P0-36","Audio trigger",FileAccess.file_exists("res://audio/ui_click.wav"),"audio file available")
    t("P0-37","Second artifact purchase",gs.buy_artifact(1),"second purchase")
    t("P0-38","No NaN/Inf",not is_nan(float(gs.money)) and not is_inf(float(gs.money)),"finite economy")
    t("P0-39","No orphan references",rr.runtime_model_paths.size()>=50,"model refs")
    t("P0-40","No fatal missing assets",rr.runtime_model_paths.size()==rr.specs.size(),"all specs mapped")
    var passed=0; for x in results: if x.passed: passed+=1
    var out={"tests":results,"executed":results.size(),"passed":passed,"failed":results.size()-passed}; var f=FileAccess.open("res://qa/R2_P0_TESTS.json",FileAccess.WRITE); f.store_string(JSON.stringify(out,"  ")); f.close(); print(JSON.stringify(out)); quit(0 if passed==results.size() else 1)
